# Generated by Django 4.2.5 on 2023-11-01 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='category_name',
        ),
    ]
