# Generated by Django 4.2.5 on 2023-11-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_product_name_products_sub_category_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='SubCategory',
        ),
    ]
