# Generated by Django 4.2.5 on 2023-11-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myproduct',
            old_name='category',
            new_name='sub_category',
        ),
    ]
